### ISSUE TITLE
Search Bar without the SideBar

### ISSUE THREAD

**Issue by halufa** [bung87/leaflet-searchbox#1]
Following your example it works very well:
`const control = new L.Control.SearchBox({
			// remove these if dont need sidebar
			
			sidebarTitleText: 'Header',
			sidebarMenuItems: {
				Items: [
					{ type: "link", name: "Link 1 (github.com)", href: "http://github.com", icon: "icon-local-carwash" },
					{ type: "link", name: "Link 2 (google.com)", href: "http://google.com", icon: "icon-cloudy" },
					{ type: "button", name: "Button 1", onclick: "alert('button 1 clicked !')", icon: "icon-potrait" },
					{ type: "button", name: "Button 2", onclick: "button2_click();", icon: "icon-local-dining" },
					{ type: "link", name: "Link 3 (stackoverflow.com)", href: 'http://stackoverflow.com', icon: "icon-bike" },
		 
				]
			}
		})`

But if I comment the options it doesn't work.
With the code:
`const control = new L.Control.SearchBox()`

Will give the error:
ERROR TypeError: Cannot read property 'sidebarTitleText' of undefined MarkerClusterDemoComponent.ngfactory.js? [sm]:1
at NewClass.initialize (leaflet.searchbox.umd.js:1299)

Can you make a quick fix for this please? Thank you :)

P.S. the package is awesome, btw!

**Comment by bung87** [comment]
@halufa  I just fixed it now, also update dependency ,  since 1.0.5 , as I publish it very quikely I using wrong method to pack it, v1.0.4-b is wrong package.

**Comment by bung87** [comment]
since 1.0.6,  allow no sidebar, also adjust the left padding. I use my fork version toolchain avoiding donwload phantomjs or puppeteer, as svg-sprite depends on it , make it as peer dependency, it only required if sprites contains svg and svg dont have viewbox that's extreme condition, when this occurs just console.log information to user .

**Comment by halufa** [comment]
It's working well. I'll let you know if I find any more issues. Thanks a lot.

**Comment by bung87** [comment]
OK，thanks for feedback,then I can sleep well :)
